language: go
go:
  - tip
before_install:
  - go get golang.org/x/tools/cmd/cover
go_import_path: github.com/pdupub/go-pdu
sudo: false
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      go: 1.18.x
      script:
        - make install
        - GO111MODULE=on
        - go test ./core

    - os: linux
      dist: xenial
      sudo: required
      go: 1.19.x
      script:
        - make install
        - GO111MODULE=on
        - go test ./core

    - os: osx
      go: 1.19.x
      script:
        - make install
        - GO111MODULE=on
        - go test ./core
